version: "3"
services:
  HubService:
    image: selenium/hub:latest
    container_name: seleniumHub
    ports:
      - "4444:4444" 
      - "4442:4442"
      - "4443:4443"

  FirefoxService:
    image: selenium/node-firefox:latest
    shm_size: "2gb"
    ports:
      - "5900"  
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true 
    depends_on:
      - HubService  
